//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace midproject_01.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CalDBEntities : DbContext
    {
        public CalDBEntities()
            : base("name=CalDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Calorie> Calories { get; set; }
        public virtual DbSet<CalorieList> CalorieLists { get; set; }
        public virtual DbSet<CarbohydrateList> CarbohydrateLists { get; set; }
        public virtual DbSet<GoodCar> GoodCars { get; set; }
        public virtual DbSet<HighProtein> HighProteins { get; set; }
        public virtual DbSet<List> Lists { get; set; }
        public virtual DbSet<Memberlist> Memberlists { get; set; }
        public virtual DbSet<PersonCal> PersonCals { get; set; }
        public virtual DbSet<Personrecord> Personrecords { get; set; }
        public virtual DbSet<ProteinList> ProteinLists { get; set; }
        public virtual DbSet<SportCoe> SportCoes { get; set; }
    }
}
