//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace midproject_01.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personrecord
    {
        public int RecordID { get; set; }
        public int MemberID { get; set; }
        public string UserName { get; set; }
        public Nullable<float> Age { get; set; }
        public Nullable<float> Height { get; set; }
        public Nullable<float> Weight { get; set; }
        public Nullable<float> BMI { get; set; }
        public Nullable<float> BMR { get; set; }
        public string ActivityCoefficient { get; set; }
        public Nullable<int> SuitableCaloriePerDay { get; set; }
        public string Measureday { get; set; }
    
        public virtual Memberlist Memberlist { get; set; }
    }
}
